### ISSUE TITLE
General TODO before release

### ISSUE THREAD

**Issue by robertpsoane** [robertpsoane/py-fighter#93]
I'm adding this General TODO as an issue here that we can all add things that need doing, and tick them off as and when done
Mainly because I keep thinking of things and don't want to forget them :')
You should be able to tick things off when done, and feel free to add more stuff as and when 💯 

## Coding Features
- [x] Camera Tracking (issue #65) - High Priority - @RokasDan 
- [x] Fix tile rect - High Priority - @RokasDan 
- [x] Weapons Animation - High Priority - @ShayLn 
- [x] Game Flow Controls TODO on Thursday - High Priority -  @robertpsoane @RokasDan @ShayLn
- - [x] More enemies with each game
- [x] SFX - Medium Priority
- [x] Score/High Score - Medium Priority @robertpsoane 
- [x] Extra Backgrounds - Medium Priority - If we do it probably @RokasDan 
- [ ] PVP - Medium/Low Priority

- [x] Settings - Low Priority

## Documentation For Submission
- [x] **Ensure all code documenter**
- [x] Complete contrib file
- [x] README file
- [x] Description file - also going on website
